// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mm2s_mm2s,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcve2802-vsvh1760-2MP-e-S,HLS_INPUT_CLOCK=3.200000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.194000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1585,HLS_SYN_LUT=1646,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module mm2s (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_TDATA,
        s_TVALID,
        s_TREADY,
        s_TKEEP,
        s_TSTRB,
        s_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 78'd1;
parameter    ap_ST_fsm_state2 = 78'd2;
parameter    ap_ST_fsm_state3 = 78'd4;
parameter    ap_ST_fsm_state4 = 78'd8;
parameter    ap_ST_fsm_state5 = 78'd16;
parameter    ap_ST_fsm_state6 = 78'd32;
parameter    ap_ST_fsm_state7 = 78'd64;
parameter    ap_ST_fsm_state8 = 78'd128;
parameter    ap_ST_fsm_state9 = 78'd256;
parameter    ap_ST_fsm_state10 = 78'd512;
parameter    ap_ST_fsm_state11 = 78'd1024;
parameter    ap_ST_fsm_state12 = 78'd2048;
parameter    ap_ST_fsm_state13 = 78'd4096;
parameter    ap_ST_fsm_state14 = 78'd8192;
parameter    ap_ST_fsm_state15 = 78'd16384;
parameter    ap_ST_fsm_state16 = 78'd32768;
parameter    ap_ST_fsm_state17 = 78'd65536;
parameter    ap_ST_fsm_state18 = 78'd131072;
parameter    ap_ST_fsm_state19 = 78'd262144;
parameter    ap_ST_fsm_state20 = 78'd524288;
parameter    ap_ST_fsm_state21 = 78'd1048576;
parameter    ap_ST_fsm_state22 = 78'd2097152;
parameter    ap_ST_fsm_state23 = 78'd4194304;
parameter    ap_ST_fsm_state24 = 78'd8388608;
parameter    ap_ST_fsm_state25 = 78'd16777216;
parameter    ap_ST_fsm_state26 = 78'd33554432;
parameter    ap_ST_fsm_state27 = 78'd67108864;
parameter    ap_ST_fsm_state28 = 78'd134217728;
parameter    ap_ST_fsm_state29 = 78'd268435456;
parameter    ap_ST_fsm_state30 = 78'd536870912;
parameter    ap_ST_fsm_state31 = 78'd1073741824;
parameter    ap_ST_fsm_state32 = 78'd2147483648;
parameter    ap_ST_fsm_state33 = 78'd4294967296;
parameter    ap_ST_fsm_state34 = 78'd8589934592;
parameter    ap_ST_fsm_state35 = 78'd17179869184;
parameter    ap_ST_fsm_state36 = 78'd34359738368;
parameter    ap_ST_fsm_state37 = 78'd68719476736;
parameter    ap_ST_fsm_state38 = 78'd137438953472;
parameter    ap_ST_fsm_state39 = 78'd274877906944;
parameter    ap_ST_fsm_state40 = 78'd549755813888;
parameter    ap_ST_fsm_state41 = 78'd1099511627776;
parameter    ap_ST_fsm_state42 = 78'd2199023255552;
parameter    ap_ST_fsm_state43 = 78'd4398046511104;
parameter    ap_ST_fsm_state44 = 78'd8796093022208;
parameter    ap_ST_fsm_state45 = 78'd17592186044416;
parameter    ap_ST_fsm_state46 = 78'd35184372088832;
parameter    ap_ST_fsm_state47 = 78'd70368744177664;
parameter    ap_ST_fsm_state48 = 78'd140737488355328;
parameter    ap_ST_fsm_state49 = 78'd281474976710656;
parameter    ap_ST_fsm_state50 = 78'd562949953421312;
parameter    ap_ST_fsm_state51 = 78'd1125899906842624;
parameter    ap_ST_fsm_state52 = 78'd2251799813685248;
parameter    ap_ST_fsm_state53 = 78'd4503599627370496;
parameter    ap_ST_fsm_state54 = 78'd9007199254740992;
parameter    ap_ST_fsm_state55 = 78'd18014398509481984;
parameter    ap_ST_fsm_state56 = 78'd36028797018963968;
parameter    ap_ST_fsm_state57 = 78'd72057594037927936;
parameter    ap_ST_fsm_state58 = 78'd144115188075855872;
parameter    ap_ST_fsm_state59 = 78'd288230376151711744;
parameter    ap_ST_fsm_state60 = 78'd576460752303423488;
parameter    ap_ST_fsm_state61 = 78'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 78'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 78'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 78'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 78'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 78'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 78'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 78'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 78'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 78'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 78'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 78'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 78'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 78'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 78'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 78'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 78'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 78'd151115727451828646838272;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output  [31:0] s_TDATA;
output   s_TVALID;
input   s_TREADY;
output  [3:0] s_TKEEP;
output  [3:0] s_TSTRB;
output  [0:0] s_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [77:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] mem;
wire   [31:0] size;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [31:0] size_read_reg_175;
reg    ap_block_state1;
wire   [30:0] trunc_ln14_fu_119_p1;
reg   [30:0] trunc_ln14_reg_182;
wire  signed [61:0] trunc_ln_fu_128_p4;
reg   [61:0] trunc_ln_reg_187;
wire    gmem_0_AWREADY;
wire    gmem_0_WREADY;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
reg   [63:0] gmem_0_ARADDR;
reg   [31:0] gmem_0_ARLEN;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
wire   [63:0] zext_ln14_fu_156_p1;
wire   [31:0] add_ln20_fu_169_p2;
reg   [31:0] add_ln20_reg_202;
wire    ap_CS_fsm_state76;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_done;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_idle;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_ready;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WVALID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WDATA;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WSTRB;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WLAST;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WID;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARID;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARUSER;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_RREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_BREADY;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TREADY;
wire   [31:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TDATA;
wire    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TKEEP;
wire   [3:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TSTRB;
wire   [0:0] grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TLAST;
reg    grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start_reg;
wire    ap_CS_fsm_state77;
reg   [31:0] s_TDATA_reg;
reg   [3:0] s_TKEEP_reg;
reg   [3:0] s_TSTRB_reg;
reg   [0:0] s_TLAST_reg;
wire  signed [63:0] sext_ln14_fu_138_p1;
wire   [0:0] icmp_ln14_fu_123_p2;
wire   [30:0] empty_fu_149_p3;
wire    ap_CS_fsm_state78;
wire    regslice_both_s_V_data_V_U_apdone_blk;
reg   [77:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
reg    ap_ST_fsm_state78_blk;
reg   [31:0] s_TDATA_int_regslice;
wire    s_TVALID_int_regslice;
wire    s_TREADY_int_regslice;
wire    regslice_both_s_V_data_V_U_vld_out;
wire    regslice_both_s_V_keep_V_U_apdone_blk;
reg   [3:0] s_TKEEP_int_regslice;
wire    regslice_both_s_V_keep_V_U_ack_in_dummy;
wire    regslice_both_s_V_keep_V_U_vld_out;
wire    regslice_both_s_V_strb_V_U_apdone_blk;
reg   [3:0] s_TSTRB_int_regslice;
wire    regslice_both_s_V_strb_V_U_ack_in_dummy;
wire    regslice_both_s_V_strb_V_U_vld_out;
wire    regslice_both_s_V_last_V_U_apdone_blk;
reg   [0:0] s_TLAST_int_regslice;
wire    regslice_both_s_V_last_V_U_ack_in_dummy;
wire    regslice_both_s_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 78'd1;
#0 grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start_reg = 1'b0;
end

mm2s_mm2s_Pipeline_VITIS_LOOP_14_1 grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start),
    .ap_done(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_done),
    .ap_idle(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_idle),
    .ap_ready(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .s_TREADY(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TREADY),
    .size(size_read_reg_175),
    .sext_ln14(trunc_ln_reg_187),
    .add_ln20(add_ln20_reg_202),
    .s_TDATA(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TDATA),
    .s_TVALID(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID),
    .s_TKEEP(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TKEEP),
    .s_TSTRB(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TSTRB),
    .s_TLAST(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TLAST)
);

mm2s_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mem(mem),
    .size(size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

mm2s_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 73 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(gmem_0_ARADDR),
    .I_CH0_ARLEN(gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

mm2s_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_TDATA_int_regslice),
    .vld_in(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID),
    .ack_in(s_TREADY_int_regslice),
    .data_out(s_TDATA),
    .vld_out(regslice_both_s_V_data_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_data_V_U_apdone_blk)
);

mm2s_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_TKEEP_int_regslice),
    .vld_in(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID),
    .ack_in(regslice_both_s_V_keep_V_U_ack_in_dummy),
    .data_out(s_TKEEP),
    .vld_out(regslice_both_s_V_keep_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_keep_V_U_apdone_blk)
);

mm2s_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_TSTRB_int_regslice),
    .vld_in(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID),
    .ack_in(regslice_both_s_V_strb_V_U_ack_in_dummy),
    .data_out(s_TSTRB),
    .vld_out(regslice_both_s_V_strb_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_strb_V_U_apdone_blk)
);

mm2s_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_TLAST_int_regslice),
    .vld_in(grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID),
    .ack_in(regslice_both_s_V_last_V_U_ack_in_dummy),
    .data_out(s_TLAST),
    .vld_out(regslice_both_s_V_last_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_s_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state78))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state76)) begin
            grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start_reg <= 1'b1;
        end else if ((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_ready == 1'b1)) begin
            grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        add_ln20_reg_202 <= add_ln20_fu_169_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        s_TDATA_reg <= grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TDATA;
        s_TKEEP_reg <= grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TKEEP;
        s_TLAST_reg <= grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TLAST;
        s_TSTRB_reg <= grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        size_read_reg_175 <= size;
        trunc_ln14_reg_182 <= trunc_ln14_fu_119_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln_reg_187 <= {{mem[63:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

always @ (*) begin
    if ((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_done == 1'b0)) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_s_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state78_blk = 1'b1;
    end else begin
        ap_ST_fsm_state78_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_s_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_s_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_ARADDR = sext_ln14_fu_138_p1;
    end else if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem_0_ARADDR = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARADDR;
    end else begin
        gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_ARLEN = zext_ln14_fu_156_p1;
    end else if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem_0_ARLEN = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARLEN;
    end else begin
        gmem_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem_0_ARVALID = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_ARVALID;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem_0_RREADY = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_m_axi_gmem_0_RREADY;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        s_TDATA_int_regslice = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TDATA;
    end else begin
        s_TDATA_int_regslice = s_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        s_TKEEP_int_regslice = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TKEEP;
    end else begin
        s_TKEEP_int_regslice = s_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        s_TLAST_int_regslice = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TLAST;
    end else begin
        s_TLAST_int_regslice = s_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        s_TSTRB_int_regslice = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TSTRB;
    end else begin
        s_TSTRB_int_regslice = s_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            if (((grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        ap_ST_fsm_state78 : begin
            if (((regslice_both_s_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state78))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_fu_169_p2 = ($signed(size_read_reg_175) + $signed(32'd4294967295));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign empty_fu_149_p3 = ((icmp_ln14_fu_123_p2[0:0] == 1'b1) ? trunc_ln14_reg_182 : 31'd0);

assign grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_ap_start_reg;

assign grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TREADY = (s_TREADY_int_regslice & ap_CS_fsm_state77);

assign icmp_ln14_fu_123_p2 = (($signed(size_read_reg_175) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign s_TVALID = regslice_both_s_V_data_V_U_vld_out;

assign s_TVALID_int_regslice = grp_mm2s_Pipeline_VITIS_LOOP_14_1_fu_102_s_TVALID;

assign sext_ln14_fu_138_p1 = trunc_ln_fu_128_p4;

assign trunc_ln14_fu_119_p1 = size[30:0];

assign trunc_ln_fu_128_p4 = {{mem[63:2]}};

assign zext_ln14_fu_156_p1 = empty_fu_149_p3;

endmodule //mm2s
